/*
 * This source file was generated by the Gradle 'init' task
 */
package GPT;

import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        // Chạy giao diện trong EDT (Event Dispatch Thread)
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                GUI_VehicleManager gui = new GUI_VehicleManager();
                gui.setVisible(true);
            }
        });
    }
}
